"""
Crystallographic root systems, Weyl reflections, and Dynkin diagram classification.

Summary:
    RootSystem model, Weyl group reflections, Euclidean embedding, and ASCII Dynkin diagrams.
"""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass
from typing import TYPE_CHECKING, Literal

if TYPE_CHECKING:
    from algebrax.lie.core import LieAlgebra


def _standard_cartan_matrix(family: str, rank: int | None = None) -> tuple[list[list[int]], str, int]:
    """Return the standard integer Cartan matrix, canonical label, and rank for a Dynkin type."""
    fam = family.upper().strip()
    if fam in ('G2', 'G'):
        return [[2, -1], [-3, 2]], 'G2', 2
    if fam in ('F4', 'F'):
        return (
            [
                [2, -1, 0, 0],
                [-1, 2, -2, 0],
                [0, -1, 2, -1],
                [0, 0, -1, 2],
            ],
            'F4',
            4,
        )
    if fam in ('E6',):
        return (
            [
                [2, 0, -1, 0, 0, 0],
                [0, 2, 0, -1, 0, 0],
                [-1, 0, 2, -1, 0, 0],
                [0, -1, -1, 2, -1, 0],
                [0, 0, 0, -1, 2, -1],
                [0, 0, 0, 0, -1, 2],
            ],
            'E6',
            6,
        )
    if fam in ('E7',):
        return (
            [
                [2, 0, -1, 0, 0, 0, 0],
                [0, 2, 0, -1, 0, 0, 0],
                [-1, 0, 2, -1, 0, 0, 0],
                [0, -1, -1, 2, -1, 0, 0],
                [0, 0, 0, -1, 2, -1, 0],
                [0, 0, 0, 0, -1, 2, -1],
                [0, 0, 0, 0, 0, -1, 2],
            ],
            'E7',
            7,
        )
    if fam in ('E8',):
        return (
            [
                [2, 0, -1, 0, 0, 0, 0, 0],
                [0, 2, 0, -1, 0, 0, 0, 0],
                [-1, 0, 2, -1, 0, 0, 0, 0],
                [0, -1, -1, 2, -1, 0, 0, 0],
                [0, 0, 0, -1, 2, -1, 0, 0],
                [0, 0, 0, 0, -1, 2, -1, 0],
                [0, 0, 0, 0, 0, -1, 2, -1],
                [0, 0, 0, 0, 0, 0, -1, 2],
            ],
            'E8',
            8,
        )

    # Classical series A_n, B_n, C_n, D_n
    if rank is None:
        raise ValueError(f'Rank must be specified for classical family {fam}.')
    if fam == 'A':
        if rank < 1:
            raise ValueError('A_n requires rank >= 1.')
        mat = [[2 if i == j else (-1 if abs(i - j) == 1 else 0) for j in range(rank)] for i in range(rank)]
        return mat, f'A{rank}', rank
    if fam == 'B':
        if rank < 2:
            raise ValueError('B_n requires rank >= 2.')
        mat = [[2 if i == j else (-1 if abs(i - j) == 1 else 0) for j in range(rank)] for i in range(rank)]
        mat[rank - 2][rank - 1] = -2
        mat[rank - 1][rank - 2] = -1
        return mat, f'B{rank}', rank
    if fam == 'C':
        if rank < 2:
            raise ValueError('C_n requires rank >= 2.')
        mat = [[2 if i == j else (-1 if abs(i - j) == 1 else 0) for j in range(rank)] for i in range(rank)]
        mat[rank - 2][rank - 1] = -1
        mat[rank - 1][rank - 2] = -2
        return mat, f'C{rank}', rank
    if fam == 'D':
        if rank < 4:
            raise ValueError('D_n requires rank >= 4.')
        mat = [[2 if i == j else (-1 if abs(i - j) == 1 else 0) for j in range(rank)] for i in range(rank)]
        mat[rank - 2][rank - 1] = 0
        mat[rank - 1][rank - 2] = 0
        mat[rank - 3][rank - 1] = -1
        mat[rank - 1][rank - 3] = -1
        return mat, f'D{rank}', rank

    raise ValueError(f"Unknown Dynkin family '{family}'. Supported: 'A', 'B', 'C', 'D', 'G2', 'F4', 'E6', 'E7', 'E8'.")


@dataclass(frozen=True)
class RootSystem:
    r"""Crystallographic root system generated by simple roots and Weyl reflections.

    Algebraic Signature:
        $\Phi \subset \mathbb{Z}^r, \quad s_i(\alpha) = \alpha - \langle \alpha, \alpha_i^\vee \rangle \alpha_i$
    """

    cartan_matrix: list[list[int]]
    rank: int
    dynkin_type: str
    roots: list[tuple[int, ...]]
    positive_roots: list[tuple[int, ...]]
    negative_roots: list[tuple[int, ...]]
    simple_roots: list[tuple[int, ...]]
    symmetrizing_factors: list[int]

    @classmethod
    def from_cartan_matrix(cls, cartan: Sequence[Sequence[int]], dynkin_type: str = 'Custom') -> RootSystem:
        """Construct RootSystem from a square integer Cartan matrix."""
        r = len(cartan)
        c_mat = [list(row) for row in cartan]
        simple = [tuple(1 if k == i else 0 for k in range(r)) for i in range(r)]

        def reflect(alpha: tuple[int, ...], i: int) -> tuple[int, ...]:
            val = sum(alpha[j] * c_mat[j][i] for j in range(r))
            new_a = list(alpha)
            new_a[i] -= val
            return tuple(new_a)

        pos_roots: set[tuple[int, ...]] = set(simple)
        frontier: list[tuple[int, ...]] = list(simple)
        while frontier:
            alpha = frontier.pop()
            for i in range(r):
                beta = reflect(alpha, i)
                if all(x >= 0 for x in beta) and any(x > 0 for x in beta) and beta not in pos_roots:
                    pos_roots.add(beta)
                    frontier.append(beta)

        sorted_pos = sorted(pos_roots, key=lambda a: (sum(a), a))
        sorted_neg = sorted([tuple(-x for x in a) for a in sorted_pos], key=lambda a: (-sum(a), a))
        all_roots = sorted_pos + sorted_neg

        # Symmetrizing factors d_i such that d_i A_{ij} = d_j A_{ji}
        d_factors = [1] * r
        if dynkin_type.startswith('G'):
            d_factors = [3, 1]
        elif dynkin_type.startswith('B'):
            d_factors = [2] * (r - 1) + [1]
        elif dynkin_type.startswith('C'):
            d_factors = [1] * (r - 1) + [2]
        elif dynkin_type.startswith('F'):
            d_factors = [2, 2, 1, 1]

        return cls(
            cartan_matrix=c_mat,
            rank=r,
            dynkin_type=dynkin_type,
            roots=all_roots,
            positive_roots=sorted_pos,
            negative_roots=sorted_neg,
            simple_roots=simple,
            symmetrizing_factors=d_factors,
        )

    @classmethod
    def from_dynkin(cls, family: str, rank: int | None = None) -> RootSystem:
        """Construct RootSystem from standard Dynkin classification label."""
        cartan, label, _ = _standard_cartan_matrix(family, rank)
        return cls.from_cartan_matrix(cartan, dynkin_type=label)

    def weyl_reflect(self, root: tuple[int, ...], simple_idx: int) -> tuple[int, ...]:
        """Apply simple reflection s_i(alpha) = alpha - <alpha, alpha_i^v> alpha_i."""
        val = sum(root[j] * self.cartan_matrix[j][simple_idx] for j in range(self.rank))
        new_a = list(root)
        new_a[simple_idx] -= val
        return tuple(new_a)

    def to_euclidean(self, root: tuple[int, ...]) -> tuple[float, ...]:
        """Project a root expressed in simple root coordinates Z^r to standard Euclidean space."""
        # Standard Euclidean embeddings for simple roots
        r = self.rank
        dt = self.dynkin_type
        if dt.startswith('A'):
            # e_i - e_{i+1} in R^{r+1}
            euc = [0.0] * (r + 1)
            for i, c in enumerate(root):
                euc[i] += float(c)
                euc[i + 1] -= float(c)
            return tuple(euc)
        if dt == 'G2':
            # e_1 = (0, 1, -1), e_2 = (1, -2, 1)
            euc = [0.0, 0.0, 0.0]
            c1, c2 = root[0], root[1]
            euc[0] = float(c2)
            euc[1] = float(c1 - 2 * c2)
            euc[2] = float(-c1 + c2)
            return tuple(euc)
        if dt == 'F4':
            # alpha_1 = (0, 1, -1, 0), alpha_2 = (0, 0, 1, -1), alpha_3 = (0, 0, 0, 1), alpha_4 = 0.5*(1, -1, -1, -1)
            euc = [0.0] * 4
            c1, c2, c3, c4 = root
            euc[0] = 0.5 * c4
            euc[1] = c1 - 0.5 * c4
            euc[2] = -c1 + c2 - 0.5 * c4
            euc[3] = -c2 + c3 - 0.5 * c4
            return tuple(euc)
        if dt.startswith('E'):
            # Standard E8 embeddings (subspaces for E6, E7)
            simple_e8 = [
                (0.5, -0.5, -0.5, -0.5, -0.5, -0.5, -0.5, 0.5),
                (1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
                (-1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
                (0.0, -1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0),
                (0.0, 0.0, -1.0, 1.0, 0.0, 0.0, 0.0, 0.0),
                (0.0, 0.0, 0.0, -1.0, 1.0, 0.0, 0.0, 0.0),
                (0.0, 0.0, 0.0, 0.0, -1.0, 1.0, 0.0, 0.0),
                (0.0, 0.0, 0.0, 0.0, 0.0, -1.0, 1.0, 0.0),
            ]
            euc = [0.0] * 8
            for i, c in enumerate(root):
                for k in range(8):
                    euc[k] += c * simple_e8[i][k]
            return tuple(euc)

        # Fallback: identity embedding
        return tuple(float(x) for x in root)

    def dynkin_diagram(self, format: Literal['ascii', 'mermaid', 'svg'] = 'ascii') -> str:
        """Render Coxeter-Dynkin diagram in ASCII, Mermaid, or SVG format.

        Parameters
        ----------
        format : {'ascii', 'mermaid', 'svg'}, default 'ascii'
            Output format for the diagram:
            - 'ascii': Text representation using Unicode box and arrow characters.
            - 'mermaid': Mermaid flowchart markdown string for documentation.
            - 'svg': Standalone responsive XML vector graphic with color-coded nodes.

        Returns
        -------
        str
            Rendered diagram string in the requested format.

        Raises
        ------
        ValueError
            If format is not one of 'ascii', 'mermaid', or 'svg'.
        """
        fmt = format.lower().strip()
        if fmt == 'ascii':
            return self.dynkin_ascii()
        if fmt == 'mermaid':
            return self.dynkin_mermaid()
        if fmt == 'svg':
            return self.dynkin_svg()
        raise ValueError(f"Unsupported Dynkin diagram format '{format}'. Expected 'ascii', 'mermaid', or 'svg'.")

    def dynkin_ascii(self) -> str:
        """Render publication-grade ASCII Coxeter-Dynkin diagram."""
        return _dynkin_ascii(self.dynkin_type, self.rank)

    def dynkin_mermaid(self) -> str:
        """Render Mermaid flowchart Coxeter-Dynkin diagram."""
        return _dynkin_mermaid(self.dynkin_type, self.rank)

    def dynkin_svg(self) -> str:
        """Render standalone responsive SVG Coxeter-Dynkin diagram."""
        return _dynkin_svg(self.dynkin_type, self.rank)

    def _repr_svg_(self) -> str:
        """Jupyter rich display hook for interactive SVG rendering."""
        return self.dynkin_svg()

    def __repr__(self) -> str:
        return f'RootSystem({self.dynkin_type}, rank={self.rank}, num_roots={len(self.roots)})'


def _dynkin_ascii(dt: str, r: int) -> str:
    """Render publication-grade ASCII Dynkin diagram."""
    if dt == 'G2':
        return '(1) ≡>≡ (2)'
    if dt == 'F4':
        return '(1) --- (2) ===> (3) --- (4)'
    if dt == 'E6':
        return '          (2)\n           |\n(1)---(3)-(4)-(5)-(6)'
    if dt == 'E7':
        return '          (2)\n           |\n(1)---(3)-(4)-(5)-(6)-(7)'
    if dt == 'E8':
        return '          (2)\n           |\n(1)---(3)-(4)-(5)-(6)-(7)-(8)'
    if dt.startswith('A') and (len(dt) == 1 or dt[1:].isdigit()):
        return ' --- '.join(f'({i + 1})' for i in range(r))
    if dt.startswith('B') and (len(dt) == 1 or dt[1:].isdigit()):
        chain = ' --- '.join(f'({i + 1})' for i in range(r - 1))
        return f'{chain} ===> ({r})'
    if dt == 'C' or (dt.startswith('C') and dt[1:].isdigit()):
        chain = ' --- '.join(f'({i + 1})' for i in range(r - 1))
        return f'{chain} <=== ({r})'
    if dt.startswith('D') and (len(dt) == 1 or dt[1:].isdigit()):
        chain = ' --- '.join(f'({i + 1})' for i in range(r - 2))
        return f'           ({r - 1})\n          /\n{chain}\n          \\\n           ({r})'
    return f'Dynkin({dt}, rank={r})'


def _dynkin_mermaid(dt: str, r: int) -> str:
    """Render Mermaid flowchart Coxeter-Dynkin diagram."""
    lines = ['flowchart LR']
    if dt.startswith('A') and (len(dt) == 1 or dt[1:].isdigit()):
        if r == 1:
            lines.append('    1((1))')
        else:
            for i in range(1, r):
                lines.append(f'    {i}(({i})) --- {i + 1}(({i + 1}))')
        return '\n'.join(lines)
    if dt.startswith('B') and (len(dt) == 1 or dt[1:].isdigit()):
        for i in range(1, r - 1):
            lines.append(f'    {i}(({i})) --- {i + 1}(({i + 1}))')
        lines.append(f'    {r - 1}(({r - 1})) ==> {r}(({r}))')
        return '\n'.join(lines)
    if dt == 'C' or (dt.startswith('C') and dt[1:].isdigit()):
        for i in range(1, r - 1):
            lines.append(f'    {i}(({i})) --- {i + 1}(({i + 1}))')
        lines.append(f'    {r - 1}(({r - 1})) <== {r}(({r}))')
        return '\n'.join(lines)
    if dt.startswith('D') and (len(dt) == 1 or dt[1:].isdigit()):
        for i in range(1, r - 2):
            lines.append(f'    {i}(({i})) --- {i + 1}(({i + 1}))')
        lines.append(f'    {r - 2}(({r - 2})) --- {r - 1}(({r - 1}))')
        lines.append(f'    {r - 2}(({r - 2})) --- {r}(({r}))')
        return '\n'.join(lines)
    if dt == 'G2':
        lines.append('    1((1)) ===|"⇒ (3)"| 2((2))')
        return '\n'.join(lines)
    if dt == 'F4':
        lines.extend(
            [
                '    1((1)) --- 2((2))',
                '    2((2)) ==> 3((3))',
                '    3((3)) --- 4((4))',
            ]
        )
        return '\n'.join(lines)
    if dt in ('E6', 'E7', 'E8'):
        lines.extend(
            [
                '    1((1)) --- 3((3))',
                '    3((3)) --- 4((4))',
                '    2((2)) --- 4((4))',
            ]
        )
        for i in range(4, r):
            lines.append(f'    {i}(({i})) --- {i + 1}(({i + 1}))')
        return '\n'.join(lines)
    for i in range(1, r + 1):
        lines.append(f'    {i}(({i}))')
    return '\n'.join(lines)


def _render_svg_node(cx: float, cy: float, label: str) -> str:
    """Render SVG circle node with centered bold label."""
    c_tag = f'    <circle cx="{cx:.1f}" cy="{cy:.1f}" r="14" fill="#2563eb" stroke="#1d4ed8" stroke-width="2"/>'
    t_tag = (
        f'    <text x="{cx:.1f}" y="{cy:.1f}" font-family="system-ui, -apple-system, sans-serif" '
        f'font-size="12" font-weight="bold" fill="#ffffff" text-anchor="middle" dominant-baseline="central">'
        f'{label}</text>'
    )
    return f'{c_tag}\n{t_tag}'


def _svg_line(x1: float, y1: float, x2: float, y2: float, w: float = 2.0) -> str:
    return f'    <line x1="{x1:.1f}" y1="{y1:.1f}" x2="{x2:.1f}" y2="{y2:.1f}" stroke="#4b5563" stroke-width="{w}"/>'


def _svg_poly(pts: str) -> str:
    return f'    <polygon points="{pts}" fill="#4b5563"/>'


def _render_svg_edge(x1: float, y1: float, x2: float, y2: float, kind: str = 'single') -> str:
    """Render single, double, or triple bond SVG edge between two points."""
    if kind == 'single':
        return _svg_line(x1, y1, x2, y2, 2.0)
    mx = (x1 + x2) / 2.0
    y = y1
    if kind == 'double_right':
        l1 = _svg_line(x1, y - 3.5, x2, y - 3.5, 2.0)
        l2 = _svg_line(x1, y + 3.5, x2, y + 3.5, 2.0)
        p = _svg_poly(f'{mx + 5:.1f},{y:.1f} {mx - 4:.1f},{y - 5.5:.1f} {mx - 4:.1f},{y + 5.5:.1f}')
        return f'{l1}\n{l2}\n{p}'
    if kind == 'double_left':
        l1 = _svg_line(x1, y - 3.5, x2, y - 3.5, 2.0)
        l2 = _svg_line(x1, y + 3.5, x2, y + 3.5, 2.0)
        p = _svg_poly(f'{mx - 5:.1f},{y:.1f} {mx + 4:.1f},{y - 5.5:.1f} {mx + 4:.1f},{y + 5.5:.1f}')
        return f'{l1}\n{l2}\n{p}'
    if kind == 'triple_right':
        l1 = _svg_line(x1, y - 5.0, x2, y - 5.0, 1.8)
        l2 = _svg_line(x1, y, x2, y, 1.8)
        l3 = _svg_line(x1, y + 5.0, x2, y + 5.0, 1.8)
        p = _svg_poly(f'{mx + 6:.1f},{y:.1f} {mx - 4:.1f},{y - 6:.1f} {mx - 4:.1f},{y + 6:.1f}')
        return f'{l1}\n{l2}\n{l3}\n{p}'
    return ''


def _dynkin_svg_layout(
    dt: str, r: int
) -> tuple[int, int, list[tuple[float, float, str]], list[tuple[float, float, float, float, str]]]:
    """Compute (width, height, nodes, edges) geometry for SVG Dynkin diagram."""
    nodes: list[tuple[float, float, str]] = []
    edges: list[tuple[float, float, float, float, str]] = []

    if dt in ('E6', 'E7', 'E8'):
        w, h = 60 + (r - 2) * 60, 105
        h_order = [1, 3, 4, *list(range(5, r + 1))]
        coords = {lbl: (30.0 + idx * 60.0, 80.0) for idx, lbl in enumerate(h_order)}
        coords[2] = (coords[4][0], 25.0)
        nodes.extend((coords[lbl][0], coords[lbl][1], str(lbl)) for lbl in sorted(coords))
        edges.append((*coords[1], *coords[3], 'single'))
        edges.append((*coords[3], *coords[4], 'single'))
        edges.append((*coords[2], *coords[4], 'single'))
        for idx in range(4, r):
            edges.append((*coords[idx], *coords[idx + 1], 'single'))
        return w, h, nodes, edges

    if dt.startswith('D') and (len(dt) == 1 or dt[1:].isdigit()):
        w, h = 60 + (r - 2) * 60, 100
        for i in range(1, r - 1):
            nodes.append((30.0 + (i - 1) * 60.0, 50.0, str(i)))
        bx = 30.0 + (r - 2) * 60.0
        nodes.append((bx, 22.0, str(r - 1)))
        nodes.append((bx, 78.0, str(r)))
        for i in range(1, r - 2):
            edges.append((nodes[i - 1][0], 50.0, nodes[i][0], 50.0, 'single'))
        fork_x = nodes[r - 3][0]
        edges.append((fork_x, 50.0, bx, 22.0, 'single'))
        edges.append((fork_x, 50.0, bx, 78.0, 'single'))
        return w, h, nodes, edges

    w, h = max(60, 60 + (r - 1) * 60), 70
    for i in range(1, r + 1):
        nodes.append((30.0 + (i - 1) * 60.0, 35.0, str(i)))

    if dt == 'G2':
        edges.append((nodes[0][0], 35.0, nodes[1][0], 35.0, 'triple_right'))
    elif dt == 'F4':
        edges.append((nodes[0][0], 35.0, nodes[1][0], 35.0, 'single'))
        edges.append((nodes[1][0], 35.0, nodes[2][0], 35.0, 'double_right'))
        edges.append((nodes[2][0], 35.0, nodes[3][0], 35.0, 'single'))
    elif dt.startswith('B') and (len(dt) == 1 or dt[1:].isdigit()):
        for i in range(r - 2):
            edges.append((nodes[i][0], 35.0, nodes[i + 1][0], 35.0, 'single'))
        if r >= 2:
            edges.append((nodes[r - 2][0], 35.0, nodes[r - 1][0], 35.0, 'double_right'))
    elif dt == 'C' or (dt.startswith('C') and dt[1:].isdigit()):
        for i in range(r - 2):
            edges.append((nodes[i][0], 35.0, nodes[i + 1][0], 35.0, 'single'))
        if r >= 2:
            edges.append((nodes[r - 2][0], 35.0, nodes[r - 1][0], 35.0, 'double_left'))
    elif dt.startswith('A') and (len(dt) == 1 or dt[1:].isdigit()):
        for i in range(r - 1):
            edges.append((nodes[i][0], 35.0, nodes[i + 1][0], 35.0, 'single'))

    return w, h, nodes, edges


def _dynkin_svg(dt: str, r: int) -> str:
    """Render standalone responsive SVG Coxeter-Dynkin diagram."""
    w, h, nodes, edges = _dynkin_svg_layout(dt, r)
    svg_edges = [_render_svg_edge(*e) for e in edges]
    svg_nodes = [_render_svg_node(cx, cy, lbl) for cx, cy, lbl in nodes]
    svg_parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {w} {h}" width="{w}" height="{h}">',
        '  <g class="dynkin-diagram">',
        *svg_edges,
        *svg_nodes,
        '  </g>',
        '</svg>',
    ]
    return '\n'.join(svg_parts)


def chevalley_lie_algebra(
    cartan_or_root_system: RootSystem | Sequence[Sequence[int]] | str,
    rank: int | None = None,
    names: Sequence[str] | None = None,
) -> LieAlgebra:
    """Construct a finite-dimensional simple Lie algebra in the Chevalley basis.

    Supports all Dynkin types:
    - Classical: A_n (su(n+1)), B_n (so(2n+1)), C_n (sp(2n)), D_n (so(2n)).
    - Exceptional: G_2 (dim 14), F_4 (dim 52), E_6 (dim 78), E_7 (dim 133), E_8 (dim 248).
    """
    if isinstance(cartan_or_root_system, str):
        rs = RootSystem.from_dynkin(cartan_or_root_system, rank=rank)
    elif isinstance(cartan_or_root_system, RootSystem):
        rs = cartan_or_root_system
    else:
        rs = RootSystem.from_cartan_matrix(cartan_or_root_system)

    dt = rs.dynkin_type
    if dt == 'G2':
        from algebrax.lie.exceptional import g2

        return g2()
    if dt == 'F4':
        from algebrax.lie.exceptional import f4

        return f4()
    if dt == 'E6':
        from algebrax.lie.exceptional import e6

        return e6()
    if dt == 'E7':
        from algebrax.lie.exceptional import e7

        return e7()
    if dt == 'E8':
        from algebrax.lie.exceptional import e8

        return e8()
    if dt.startswith('A') and (len(dt) == 1 or dt[1:].isdigit()):
        from algebrax.lie.classical import su_n

        return su_n(rs.rank + 1)
    if dt.startswith('B') and (len(dt) == 1 or dt[1:].isdigit()):
        from algebrax.lie.classical import so_n

        return so_n(2 * rs.rank + 1)
    if dt == 'C' or (dt.startswith('C') and dt[1:].isdigit()):
        from algebrax.lie.classical import sp_n

        return sp_n(rs.rank)
    if dt.startswith('D') and (len(dt) == 1 or dt[1:].isdigit()):
        from algebrax.lie.classical import so_n

        return so_n(2 * rs.rank)

    from algebrax.lie.exceptional import _build_simply_laced_algebra

    return _build_simply_laced_algebra(rs, names=names)


__all__ = [
    'RootSystem',
    'chevalley_lie_algebra',
]
